import { boolean, integer, jsonb, pgTable, real, text, timestamp, uuid } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id:text('id').primaryKey(), name:text('name').notNull(), email:text('email').notNull().unique(), emailVerified:boolean('emailVerified').notNull().default(false), image:text('image'), createdAt:timestamp('createdAt').notNull().defaultNow(), updatedAt:timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id:text('id').primaryKey(), expiresAt:timestamp('expiresAt').notNull(), token:text('token').notNull().unique(), createdAt:timestamp('createdAt').notNull().defaultNow(), updatedAt:timestamp('updatedAt').notNull().defaultNow(), ipAddress:text('ipAddress'), userAgent:text('userAgent'), userId:text('userId').notNull().references(()=>user.id,{onDelete:'cascade'}) })
export const account = pgTable('account', { id:text('id').primaryKey(), accountId:text('accountId').notNull(), providerId:text('providerId').notNull(), userId:text('userId').notNull().references(()=>user.id,{onDelete:'cascade'}), accessToken:text('accessToken'), refreshToken:text('refreshToken'), idToken:text('idToken'), accessTokenExpiresAt:timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt:timestamp('refreshTokenExpiresAt'), scope:text('scope'), password:text('password'), createdAt:timestamp('createdAt').notNull().defaultNow(), updatedAt:timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id:text('id').primaryKey(), identifier:text('identifier').notNull(), value:text('value').notNull(), expiresAt:timestamp('expiresAt').notNull(), createdAt:timestamp('createdAt').defaultNow(), updatedAt:timestamp('updatedAt').defaultNow() })
export const deviceSources = pgTable('device_sources', { id:uuid('id').primaryKey().defaultRandom(), userId:text('userId').notNull(), type:text('type').notNull(), path:text('path').notNull(), label:text('label').notNull(), enabled:boolean('enabled').notNull().default(true), lastScanned:timestamp('lastScanned'), createdAt:timestamp('createdAt').notNull().defaultNow() })
export const tracks = pgTable('tracks', { id:uuid('id').primaryKey().defaultRandom(), userId:text('userId').notNull(), title:text('title').notNull(), artist:text('artist').notNull().default('Unknown Artist'), blobPathname:text('blobPathname'), blobUrl:text('blobUrl'), fileName:text('fileName').notNull(), contentType:text('contentType').notNull(), size:integer('size').notNull(), duration:real('duration'), bpm:real('bpm'), musicalKey:text('musicalKey'), isrc:text('isrc'), coverArt:text('coverArt'), genre:text('genre'), metadata:jsonb('metadata').default({}), deviceSourceId:uuid('deviceSourceId'), localPath:text('localPath'), createdAt:timestamp('createdAt').notNull().defaultNow(), updatedAt:timestamp('updatedAt').notNull().defaultNow() })
export const trackMarkers = pgTable('track_markers', { id:uuid('id').primaryKey().defaultRandom(), userId:text('userId').notNull(), trackId:uuid('trackId').notNull(), kind:text('kind').notNull(), position:real('position').notNull(), label:text('label'), createdAt:timestamp('createdAt').notNull().defaultNow() })
export const recordings = pgTable('recordings', { id:uuid('id').primaryKey().defaultRandom(), userId:text('userId').notNull(), title:text('title').notNull(), blobPathname:text('blobPathname').notNull(), blobUrl:text('blobUrl'), duration:real('duration'), createdAt:timestamp('createdAt').notNull().defaultNow() })
